/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeminarIndexRouteImport } from './routes/seminar/index'
import { Route as ProfIndexRouteImport } from './routes/prof/index'
import { Route as FacilityIndexRouteImport } from './routes/facility/index'
import { Route as SeminarIdRouteImport } from './routes/seminar/$id'
import { Route as ProfIdRouteImport } from './routes/prof/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarIndexRoute = SeminarIndexRouteImport.update({
  id: '/seminar/',
  path: '/seminar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfIndexRoute = ProfIndexRouteImport.update({
  id: '/prof/',
  path: '/prof/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityIndexRoute = FacilityIndexRouteImport.update({
  id: '/facility/',
  path: '/facility/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarIdRoute = SeminarIdRouteImport.update({
  id: '/seminar/$id',
  path: '/seminar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfIdRoute = ProfIdRouteImport.update({
  id: '/prof/$id',
  path: '/prof/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prof/$id': typeof ProfIdRoute
  '/seminar/$id': typeof SeminarIdRoute
  '/facility/': typeof FacilityIndexRoute
  '/prof/': typeof ProfIndexRoute
  '/seminar/': typeof SeminarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prof/$id': typeof ProfIdRoute
  '/seminar/$id': typeof SeminarIdRoute
  '/facility': typeof FacilityIndexRoute
  '/prof': typeof ProfIndexRoute
  '/seminar': typeof SeminarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prof/$id': typeof ProfIdRoute
  '/seminar/$id': typeof SeminarIdRoute
  '/facility/': typeof FacilityIndexRoute
  '/prof/': typeof ProfIndexRoute
  '/seminar/': typeof SeminarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prof/$id'
    | '/seminar/$id'
    | '/facility/'
    | '/prof/'
    | '/seminar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prof/$id' | '/seminar/$id' | '/facility' | '/prof' | '/seminar'
  id:
    | '__root__'
    | '/'
    | '/prof/$id'
    | '/seminar/$id'
    | '/facility/'
    | '/prof/'
    | '/seminar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfIdRoute: typeof ProfIdRoute
  SeminarIdRoute: typeof SeminarIdRoute
  FacilityIndexRoute: typeof FacilityIndexRoute
  ProfIndexRoute: typeof ProfIndexRoute
  SeminarIndexRoute: typeof SeminarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminar/': {
      id: '/seminar/'
      path: '/seminar'
      fullPath: '/seminar/'
      preLoaderRoute: typeof SeminarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prof/': {
      id: '/prof/'
      path: '/prof'
      fullPath: '/prof/'
      preLoaderRoute: typeof ProfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/': {
      id: '/facility/'
      path: '/facility'
      fullPath: '/facility/'
      preLoaderRoute: typeof FacilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminar/$id': {
      id: '/seminar/$id'
      path: '/seminar/$id'
      fullPath: '/seminar/$id'
      preLoaderRoute: typeof SeminarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prof/$id': {
      id: '/prof/$id'
      path: '/prof/$id'
      fullPath: '/prof/$id'
      preLoaderRoute: typeof ProfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfIdRoute: ProfIdRoute,
  SeminarIdRoute: SeminarIdRoute,
  FacilityIndexRoute: FacilityIndexRoute,
  ProfIndexRoute: ProfIndexRoute,
  SeminarIndexRoute: SeminarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
